/**
 * AWS Amplify Configuration
 * 
 * Configures Amplify for the frontend application.
 * For development, you can either:
 * 1. Use outputs.json (generated by `npx ampx generate outputs`)
 * 2. Configure manually using environment variables
 */

import { Amplify } from 'aws-amplify';

/**
 * Configure Amplify
 * Tries to load from amplify_outputs.json first, then falls back to environment variables
 */
export function configureAmplify() {
  let amplifyConfig: any = null;

  // Try to load outputs.json (generated by Amplify Gen 2)
  // In development, generate this with: npx ampx generate outputs --app-id <app-id> --branch <branch>
  try {
    // Dynamic import for outputs.json - will be undefined if file doesn't exist
    // Note: This requires the file to be in the public directory or imported at build time
    // For now, we'll use environment variables as fallback
  } catch (error) {
    console.log('[Amplify Config] outputs.json not found, using manual configuration');
  }

  // Manual configuration (for development)
  if (!amplifyConfig) {
    // For local development, you'll need to set these environment variables
    // or configure manually after deploying your Amplify backend
    const userPoolId = import.meta.env.VITE_AWS_USER_POOL_ID;
    const userPoolClientId = import.meta.env.VITE_AWS_USER_POOL_CLIENT_ID;
    
    if (userPoolId && userPoolClientId) {
      amplifyConfig = {
        Auth: {
          Cognito: {
            userPoolId,
            userPoolClientId,
            loginWith: {
              email: true,
            },
          },
        },
      };
    }
  }

  // Only configure if we have at least user pool ID
  if (amplifyConfig?.Auth?.Cognito?.userPoolId) {
    Amplify.configure(amplifyConfig);
    console.log('[Amplify Config] Amplify configured successfully');
    return true;
  } else {
    console.warn('[Amplify Config] Amplify not configured - email/password auth will not work until backend is deployed');
    console.warn('[Amplify Config] Set VITE_AWS_USER_POOL_ID and VITE_AWS_USER_POOL_CLIENT_ID or deploy backend and generate outputs.json');
    return false;
  }
}

